---
- name: Static DNS Setup Aliases
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.host }}$'
    line: "{{ item.ip }} {{ item.host }}"
    state: present
  with_items: "{{ dns_aliases }}"
