---
- name: OpenSSL - Installed
  become: true
  yum:
    name: openssl
    state: present

- name: SELinux dependencies
  become: true
  yum:
    name:
      - libselinux-python
      - libsemanage-python
    state: latest

# required to allow mod_proxy to make outbound connections
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: true
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
