---
- name: Pre Req Tasks
  hosts: all
  tasks:
  - name: Pre Req Tasks
    include_tasks: tasks/prereqs.yaml

- name: Setup DNS
  hosts: all
  tasks:
  - name: DNS Tasks
    include_tasks: tasks/dns.yaml

- name: Setup wwwdata
  hosts: app
  tasks:
  - name: wwwdata Tasks
    include_tasks: tasks/wwwdata.yaml

- name: Setup Apache
  hosts: all
  tasks:
  - name: Apache Tasks
    include_tasks: tasks/apache.yaml
